Repository framgia/sph_flutter-capstone, pull requests merged in 2022-04, with the labels that each got.

#3 header layout
  lib/main.dart
  lib/views/pages/home.dart
  lib/views/pages/sample_with_appbar.dart
  lib/views/widgets/sample_widget.dart
  lib/views/widgets/template.dart
Labels: For Code Review

#4 Added navigation UI layout
  lib/views/widgets/navigation/floating_action_button.dart
  lib/views/widgets/navigation/navigation.dart
  lib/views/widgets/navigation/navigation_button.dart
Labels: Approved by Inah, Approved by Erick

#7 [Integration] Setup Riverpod and auto_route
  README.md
  lib/main.dart
  lib/models/user.dart
  lib/state/session_provider.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/utils/routing.dart
  lib/utils/test_util.dart
  lib/views/pages/home.dart
  lib/views/pages/sample_with_appbar.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: For Code Review, Approved by Inah, Approved by Roberto

#9 [Setup] Add Linter Rules and Git hook for pre-commit
  .githooks/pre-commit
  analysis_options.yaml
  lib/consts/consts.dart
  lib/consts/global_style.dart
  lib/controllers/user_controller.dart
  lib/main.dart
  lib/services/sample_service.dart
  lib/views/dialogs/dialog.dart
  lib/views/pages/home.dart
  lib/views/pages/sample_with_appbar.dart
  lib/views/pages/session/login.dart
  lib/views/pages/session/register.dart
  lib/views/widgets/navigation/floating_action_button.dart
  lib/views/widgets/navigation/navigation.dart
  lib/views/widgets/template.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved by Inah

#11 [UI] Added reusable date field
  lib/consts/global_style.dart
  lib/main.dart
  lib/utils/test_util.dart
  lib/views/pages/sample_with_appbar.dart
  lib/views/pages/welcome.dart
  lib/views/widgets/date_field.dart
  lib/views/widgets/template.dart
  pubspec.lock
  pubspec.yaml
Labels: For Code Review, Approved by Inah, Approved by Ervin

#12 Implemented Bottom Navigation
  lib/consts/routes.dart
  lib/state/navigation_provider.dart
  lib/utils/routes/readme.md
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/utils/routing.dart
  lib/utils/test_util.dart
  lib/views/pages/account_settings.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/notifications.dart
  lib/views/pages/transactions.dart
  lib/views/widgets/date_field.dart
  lib/views/widgets/navigation/bottom_navbar.dart
  lib/views/widgets/navigation/navigation.dart
  lib/views/widgets/navigation/navigation_button.dart
  lib/views/widgets/template.dart
  pubspec.lock
  pubspec.yaml
Labels: Inah is reviewing, Approved by Gwen

#10 [UI] Implement UI for Reusable Button
  analysis_options.yaml
  lib/consts/global_style.dart
  lib/main.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/sample_with_appbar.dart
  lib/views/widgets/buttons/filled_button_text.dart
  lib/views/widgets/buttons/outline_button_text.dart
  lib/views/widgets/template.dart
Labels: Approved by Inah, Approved by Gwen

#14 [UI] Added reusable input field
  lib/consts/global_style.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/notifications.dart
  lib/views/pages/sample_with_appbar.dart
  lib/views/widgets/input/date_field.dart
  lib/views/widgets/input/input_field.dart
  lib/views/widgets/input/input_group.dart
  lib/views/widgets/navigation/bottom_navbar.dart
  lib/views/widgets/template.dart
Labels: Approved by Inah, Approved by Roberto

#13 Implement UI for Account Settings Screen
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/dashboard.dart
  lib/views/widgets/cards/elevated_card.dart
  lib/views/widgets/rounded_background.dart
  lib/views/widgets/template.dart
Labels: Approved by Inah, Approved by Gwen, has conflicts

#15 [Dashboard] Implement UI for the Greeting and Transactions Summary
  lib/consts/global_style.dart
  lib/views/pages/account_settings.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/transaction_summary.dart
  lib/views/widgets/cards/elevated_card.dart
  lib/views/widgets/template.dart
Labels: Approved by Aubrey, Approved by Ervin

#17 [Dashboard] Implement UI for the spending limit percentage section
  lib/consts/global_style.dart
  lib/state/spending_provider.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/transactions.dart
  lib/views/widgets/progress_bar.dart
Labels: Approved by Inah, Approved by Roberto

#16 [UI] Implemented tab layout with dynamic content
  lib/consts/global_style.dart
  lib/views/pages/transactions.dart
  lib/views/widgets/tabs/tab_buttons.dart
  lib/views/widgets/tabs/tab_layout.dart
Labels: Approved by Aubrey, Approved by Erick

#18 [UI] Implementing Reusable Selected Field
  lib/views/pages/notifications.dart
  lib/views/widgets/input/selected_field.dart
Labels: Approved by Inah, Approved by Gwen, has conflicts

#23 Model and Controller setup
  lib/consts/routes.dart
  lib/controllers/expense_controller.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/notifications.dart
  lib/views/pages/test/sample_crud.dart
  lib/views/widgets/navigation/bottom_navbar.dart
Labels: Approved by Inah

#19 [UI] Implement Add Expense UI
  lib/consts/routes.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/notifications.dart
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_expense.dart
  lib/views/pages/transactions/add_transaction.dart
  lib/views/widgets/cards/elevated_card.dart
  lib/views/widgets/input/date_field.dart
  lib/views/widgets/input/input_field.dart
  lib/views/widgets/input/selected_field.dart
  lib/views/widgets/navigation/bottom_navbar.dart
  lib/views/widgets/navigation/floating_action_button.dart
  lib/views/widgets/tabs/tab_buttons.dart
  lib/views/widgets/tabs/tab_content.dart
  lib/views/widgets/tabs/tab_layout.dart
Labels: High Priority, Approved by Inah, Approved by Roberto

#20 Implement UI for Currency Picker form
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/account_settings/currency_picker.dart
  lib/views/pages/account_settings/update_basic_info.dart
  pubspec.lock
  pubspec.yaml
Labels: High Priority, Approved by Aubrey, Approved by Gwen

#21 [UI] Implemented Add Income UI
  lib/views/pages/test/sample_crud.dart
  lib/views/pages/transactions/add_income.dart
  lib/views/pages/transactions/add_transaction.dart
Labels: High Priority, Inah is reviewing

#22 [Account] Implement UI for Basic Info form
  lib/consts/routes.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/account_settings/currency_picker.dart
  lib/views/pages/account_settings/update_basic_info.dart
  lib/views/widgets/buttons/outline_button_text.dart
  lib/views/widgets/input/input_field.dart
  lib/views/widgets/navigation/bottom_navbar.dart
  lib/views/widgets/template.dart
  pubspec.lock
  pubspec.yaml
Labels: Approved by Aubrey

#25 [UI] Implemented transaction history tab switch
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_transaction.dart
  lib/views/widgets/tabs/tab_buttons.dart
  lib/views/widgets/tabs/tab_layout.dart
Labels: Approved by Inah

#29 Implement reusable transaction card
  lib/consts/global_style.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/account_settings/update_basic_info.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_transaction.dart
  lib/views/widgets/cards/transaction_card.dart
  lib/views/widgets/input/input_field.dart
  lib/views/widgets/tabs/tab_buttons.dart
Labels: Approved by Aubrey

#27 Add income integration
  lib/controllers/expense_controller.dart
  lib/controllers/income_controller.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/transactions/add_income.dart
  lib/views/widgets/input/date_field.dart
  lib/views/widgets/input/input_field.dart
  lib/views/widgets/template.dart
Labels: Approved by Inah

#28 [Integration] Implement Currency setting
  lib/controllers/user_controller.dart
  lib/views/pages/account_settings/currency_picker.dart
Labels: Approved by Erron

#26 [Register] Implement UI form and integrate simple registration flow
  lib/consts/routes.dart
  lib/controllers/user_controller.dart
  lib/models/model.dart
  lib/models/model.g.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/utils/routing.dart
  lib/views/pages/account_settings/currency_picker.dart
  lib/views/pages/session/extra_logo.dart
  lib/views/pages/session/register.dart
  lib/views/pages/session/register_form.dart
Labels: Erron is reviewing

#36 Implement basic info setting
  lib/controllers/account_controller.dart
  lib/controllers/user_controller.dart
  lib/main.dart
  lib/models/model.dart
  lib/models/model.g.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/account_settings/currency_picker.dart
  lib/views/pages/account_settings/update_basic_info.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/notifications.dart
  lib/views/pages/session/register_form.dart
  lib/views/widgets/input/input_field.dart
Labels: High Priority, For Code Review

#38 [Register] Route Guard
  lib/controllers/account_controller.dart
  lib/main.dart
  test/widget_test.dart
Labels: Approved by Inah

#34 [Dashboard] Implement UI for Recent Transactions section
  lib/views/pages/dashboard.dart
  lib/views/widgets/template.dart
Labels: Approved by Inah

#32 Implement Adding Expense function
  lib/consts/consts.dart
  lib/controllers/expense_controller.dart
  lib/models/model.dart
  lib/models/model.g.dart
  lib/utils/routing.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/test/sample_crud.dart
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_expense.dart
  lib/views/widgets/cards/transaction_card.dart
  lib/views/widgets/input/selected_field.dart
Labels: High Priority, Inah is reviewing

#33 [Dashboard] Display total balance, income, and expenses
  lib/controllers/expense_controller.dart
  lib/controllers/income_controller.dart
  lib/views/pages/dashboard.dart
Labels: Approved by Aubrey

#37 [Transactions History] Display all transactions
  lib/consts/consts.dart
  lib/controllers/expense_controller.dart
  lib/controllers/income_controller.dart
  lib/controllers/transactions_controller.dart
  lib/main.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/test/sample_crud.dart
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_expense.dart
  lib/views/pages/transactions/add_income.dart
  lib/views/widgets/cards/transaction_card.dart
Labels: Approved by Erron

#41 Display dynamic recent transactions
  lib/controllers/transactions_controller.dart
  lib/views/pages/dashboard.dart
Labels: For Code Review

#40 Check/Integrate currency info to all related screens
  lib/consts/consts.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/transaction_summary.dart
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_expense.dart
  lib/views/widgets/cards/transaction_card.dart
Labels: Approved by Erron

#43 [Transaction History] Filter Expenses and Income transactions
  lib/controllers/transactions_controller.dart
  lib/views/pages/dashboard.dart
  lib/views/pages/transactions.dart
  lib/views/pages/transactions/add_expense.dart
  lib/views/pages/transactions/add_income.dart
Labels: For Code Review, Approved by Roberto

#35 [Account] Implement Spending Limit setting
  lib/controllers/spending_limit_controller.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/account_settings/account_settings.dart
  lib/views/pages/account_settings/spending_limit.dart
  lib/views/widgets/navigation/bottom_navbar.dart
Labels: High Priority, Approved by Roberto

#44 [Bug] Date in transactions list is wrong
  lib/views/pages/transactions/add_expense.dart
  lib/views/widgets/cards/transaction_card.dart
Labels: Bugfix For QA Review
