Repository framgia/sph_flutter-capstone, pull requests merged in 2022-05, with the labels that each got.

#46 Removed add transaction as child of bottom nav bar
  lib/consts/routes.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/views/widgets/navigation/bottom_navbar.dart
  lib/views/widgets/navigation/floating_action_button.dart
Labels: For Code Review

#30 [UI] Implement UI Splash Screen
  lib/main.dart
  lib/utils/routes/router.dart
  lib/utils/routes/router.gr.dart
  lib/views/pages/session/splash_screen.dart
Labels: Approved by Gwen

#47 fixed icon not highlighting by setting current page
  lib/views/pages/dashboard.dart
Labels: For Code Review

#49 [Bug] Adding expense with no selected category does not get saved to db
  lib/views/pages/transactions/add_expense.dart
Labels: For Code Review

#51 [Bug] Dashboard is not fully dynamic to any db changes - Recent Transactions
  lib/views/pages/dashboard.dart
  lib/views/pages/transaction_summary.dart
Labels: WIP

#52 [bug] Error Dashboard
  lib/views/pages/dashboard.dart
Labels: Approved by Paul
